repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^artifacts/.*  # Exclude artifacts directory
    -   id: end-of-file-fixer
        exclude: ^artifacts/.*  # Exclude artifacts directory
    -   id: check-toml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: mixed-line-ending
        args: [--fix=lf]
        exclude: ^artifacts/.*  # Exclude artifacts directory
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
    -   id: ruff-check
        args: [--fix]
    -   id: ruff-format
