name: Generate Calendar

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Run application
      run: uv run src/main.py
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        EVENTS_PAGE_URL: ${{ secrets.EVENTS_PAGE_URL }}

    - name: Commit generated files
      uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: 'feat: calendar update'
        file_pattern: 'artifacts/events.html artifacts/events.ics'
        commit_options: '--no-verify'
